# Cogent Configuration File
# This file contains main settings for the Cogent AI system

# =============================================================================
# SENSORY SETTINGS
# =============================================================================
# Configuration for processing different types of input

# Document analysis settings
[sensory.document_analysis]
model = "ollama_qwen_vision"  # Model to use for analyzing documents

# Text parsing and chunking settings
[sensory.parser]
chunk_size = 6000            # Maximum size of text chunks in characters
chunk_overlap = 300          # Number of characters to overlap between chunks
use_unstructured_api = false # Whether to use Unstructured.io API for parsing
use_contextual_chunking = false  # Whether to use AI for intelligent chunking
contextual_chunking_model = "ollama_qwen_vision"  # Model for contextual chunking

# Vision/Image processing settings
[sensory.parser.vision]
model = "ollama_qwen_vision"  # Model to use for image analysis
frame_sample_rate = -1        # How often to sample video frames (-1 = disable frame captioning)

# =============================================================================
# GRAPH SETTINGS
# =============================================================================
# Configuration for knowledge graph functionality
[graph]
model = "ollama_qwen_vision"  # Model to use for graph operations
enable_entity_resolution = true  # Whether to automatically resolve and link entities

# =============================================================================
# DATABASE SETTINGS
# =============================================================================
# Connection settings for the main database (separate from vector store)
[database]
provider = "postgres"        # Database type (postgres, mysql, sqlite)
pool_size = 10               # Maximum number of connections in the pool
max_overflow = 15            # Additional connections that can be created beyond pool_size
pool_recycle = 3600          # Time in seconds after which connections are recycled (1 hour)
pool_timeout = 10            # Seconds to wait for a connection from the pool
pool_pre_ping = true         # Check connection viability before using it
max_retries = 3              # Number of retries for database operations
retry_delay = 1.0            # Initial delay between retries in seconds
